image:
  useDigest: false
agent: false
operator:
  enabled: false
preflight:
  enabled: true
{{- if .EnableKubeProxyReplacement }}
k8sServiceHost: "{{ trimPrefix .ControlPlaneEndpoint.Host "https://" }}"
k8sServicePort: "{{ .ControlPlaneEndpoint.Port }}"
{{- end }}
