# Copyright 2023 D2iQ, Inc. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ include "chart.name" . }}
  labels:
    {{ include "chart.labels" . | nindent 4 }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
    {{- toYaml . | nindent 8 }}
{{- end }}
