agent:
  name: {{ .AgentName }}
pc:
  port: {{ .PrismCentralPort }}
  insecure: {{ .PrismCentralInsecure }}
  endpoint: {{ .PrismCentralHost }}
k8sClusterName: {{ .ClusterName }}
k8sDistribution: NKP
createSecret: false
{{- if .CategoryMappings }}
categoryMappings: {{ .CategoryMappings }}
{{- end }}
