# Copyright 2023 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2

name: cluster-api-runtime-extensions-nutanix
type: application
description: A Helm chart for cluster-api-runtime-extensions-nutanix

home: https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix
maintainers:
- name: jimmidyson
  email: jimmidyson@gmail.com
  url: https://eng.d2iq.com
sources:
- https://github.com/nutanix-cloud-native/cluster-api-runtime-extensions-nutanix
dependencies:
  - name: trust-manager
    version: v0.10.0
    repository: https://charts.jetstack.io

appVersion: v0.0.0-dev
version: v0.0.0-dev
