# Copyright 2025 Nutanix. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.hooks.konnectorAgent.helmAddonStrategy.defaultValueTemplateConfigMap.name }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ .Values.hooks.konnectorAgent.helmAddonStrategy.defaultValueTemplateConfigMap.name }}'
data:
  values.yaml: |-
    {{- .Files.Get "addons/konnector-agent/values-template.yaml" | nindent 4 }}
{{- end -}}
