# Taken from https://github.com/kubernetes/kubernetes/blob/v1.28.1/cluster/gce/gci/configure-helper.sh#L1101
# Recommended in Kubernetes docs
apiVersion: audit.k8s.io/v1
kind: Policy
rules:
# The following requests were manually identified as high-volume and low-risk,
# so drop them.
- level: None
  users: ["system:kube-proxy"]
  verbs: ["watch"]
  resources:
    - group: "" # core
      resources: ["endpoints", "services", "services/status"]
- level: None
  # Ingress controller reads 'configmaps/ingress-uid' through the unsecured port.
  # TODO(#46983): Change this to the ingress controller service account.
  users: ["system:unsecured"]
  namespaces: ["kube-system"]
  verbs: ["get"]
  resources:
    - group: "" # core
      resources: ["configmaps"]
- level: None
  users: ["kubelet"] # legacy kubelet identity
  verbs: ["get"]
  resources:
    - group: "" # core
      resources: ["nodes", "nodes/status"]
- level: None
  userGroups: ["system:nodes"]
  verbs: ["get"]
  resources:
    - group: "" # core
      resources: ["nodes", "nodes/status"]
- level: None
  users:
    - system:kube-controller-manager
    - system:cloud-controller-manager
    - system:kube-scheduler
    - system:serviceaccount:kube-system:endpoint-controller
  verbs: ["get", "update"]
  namespaces: ["kube-system"]
  resources:
    - group: "" # core
      resources: ["endpoints"]
- level: None
  users: ["system:apiserver"]
  verbs: ["get"]
  resources:
    - group: "" # core
      resources: ["namespaces", "namespaces/status", "namespaces/finalize"]
- level: None
  users: ["cluster-autoscaler"]
  verbs: ["get", "update"]
  namespaces: ["kube-system"]
  resources:
    - group: "" # core
      resources: ["configmaps", "endpoints"]
# Don't log HPA fetching metrics.
- level: None
  users:
    - system:kube-controller-manager
    - system:cloud-controller-manager
  verbs: ["get", "list"]
  resources:
    - group: "metrics.k8s.io"

# Don't log these read-only URLs.
- level: None
  nonResourceURLs:
    - /healthz*
    - /version
    - /swagger*

# Don't log events requests because of performance impact.
- level: None
  resources:
    - group: "" # core
      resources: ["events"]

# node and pod status calls from nodes are high-volume and can be large, don't log responses for expected updates from nodes
- level: Request
  users: ["kubelet", "system:node-problem-detector", "system:serviceaccount:kube-system:node-problem-detector"]
  verbs: ["update","patch"]
  resources:
    - group: "" # core
      resources: ["nodes/status", "pods/status"]
  omitStages:
    - "RequestReceived"
- level: Request
  userGroups: ["system:nodes"]
  verbs: ["update","patch"]
  resources:
    - group: "" # core
      resources: ["nodes/status", "pods/status"]
  omitStages:
    - "RequestReceived"

# deletecollection calls can be large, don't log responses for expected namespace deletions
- level: Request
  users: ["system:serviceaccount:kube-system:namespace-controller"]
  verbs: ["deletecollection"]
  omitStages:
    - "RequestReceived"

# Secrets, ConfigMaps, TokenRequest and TokenReviews can contain sensitive & binary data,
# so only log at the Metadata level.
- level: Metadata
  resources:
    - group: "" # core
      resources: ["secrets", "configmaps", "serviceaccounts/token"]
    - group: authentication.k8s.io
      resources: ["tokenreviews"]
  omitStages:
    - "RequestReceived"

# Get responses for common resources can be large; skip them.
- level: Request
  verbs: ["get", "list", "watch"]
  resources:
    - group: "" # core
    - group: "admissionregistration.k8s.io"
    - group: "apiextensions.k8s.io"
    - group: "apiregistration.k8s.io"
    - group: "apps"
    - group: "authentication.k8s.io"
    - group: "authorization.k8s.io"
    - group: "autoscaling"
    - group: "batch"
    - group: "certificates.k8s.io"
    - group: "extensions"
    - group: "metrics.k8s.io"
    - group: "networking.k8s.io"
    - group: "node.k8s.io"
    - group: "policy"
    - group: "rbac.authorization.k8s.io"
    - group: "scheduling.k8s.io"
    - group: "storage.k8s.io"
  omitStages:
    - "RequestReceived"
# Default level for common resources
- level: RequestResponse
  resources:
    - group: "" # core
    - group: "admissionregistration.k8s.io"
    - group: "apiextensions.k8s.io"
    - group: "apiregistration.k8s.io"
    - group: "apps"
    - group: "authentication.k8s.io"
    - group: "authorization.k8s.io"
    - group: "autoscaling"
    - group: "batch"
    - group: "certificates.k8s.io"
    - group: "extensions"
    - group: "metrics.k8s.io"
    - group: "networking.k8s.io"
    - group: "node.k8s.io"
    - group: "policy"
    - group: "rbac.authorization.k8s.io"
    - group: "scheduling.k8s.io"
    - group: "storage.k8s.io"
  omitStages:
    - "RequestReceived"

# Get responses for Cluster API resources can be large; skip them.
- level: Request
  verbs: ["get", "list", "watch"]
  resources:
    - group: "cluster.x-k8s.io"
    - group: "addons.cluster.x-k8s.io"
    - group: "bootstrap.cluster.x-k8s.io"
    - group: "clusterctl.cluster.x-k8s.io"
    - group: "controlplane.cluster.x-k8s.io"
    - group: "infrastructure.cluster.x-k8s.io"
    - group: "ipam.cluster.x-k8s.io"
    - group: "runtime.cluster.x-k8s.io"
  omitStages:
    - "RequestReceived"
# Default level for Cluster API resources
- level: Request
  resources:
    - group: "cluster.x-k8s.io"
    - group: "addons.cluster.x-k8s.io"
    - group: "bootstrap.cluster.x-k8s.io"
    - group: "clusterctl.cluster.x-k8s.io"
    - group: "controlplane.cluster.x-k8s.io"
    - group: "infrastructure.cluster.x-k8s.io"
    - group: "ipam.cluster.x-k8s.io"
    - group: "runtime.cluster.x-k8s.io"
  omitStages:
    - "RequestReceived"

# Default level for all other requests.
- level: Metadata
  omitStages:
    - "RequestReceived"
